spring.application.name=Finvest
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/finvest
spring.datasource.username=finvest
spring.datasource.password=finvest
spring.h2.console.enabled=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:db/dev/dev_data.sql
logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.springframework.data.jdbc.core=DEBUG
app.logger.enabled=true
app.logger.level=TRACE
cors.config.allowed-origins=http://localhost:5173
jwt.secret=une-cle-secrete-tres-longue-d-au-moins-32-caracteres
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000
config.secure=false
spring.docker.compose.file=docker/docker-compose-dev-persistent.yaml