spring.application.name=Finvest

spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always

spring.h2.console.enabled=true

spring.flyway.locations=classpath:db/migration,classpath:db/migration/dev

logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.springframework.data.jdbc.core=DEBUG

app.logger.enabled=true
app.logger.level=TRACE

cors.config.allowed-origins=http://localhost:5173

jwt.secret=une-cle-secrete-tres-longue-d-au-moins-32-caracteres
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000

config.secure=false