services:
  mariadb:
    image: mariadb:11.8
    container_name: finvest-mariadb-dev-persistent
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: finvest
      MARIADB_USER: finvest
      MARIADB_PASSWORD: finvest
    ports:
      - "3306:3306"
    volumes:
      - finvest-mariadb-persistent-data:/var/lib/mysql

volumes:
  finvest-mariadb-persistent-data: